#!/bin/bash


#Create additional buckets
influx bucket create -n ${DOCKER_INFLUXDB_SQL_SERVER_BUCKETS} -o ${DOCKER_INFLUXDB_INIT_ORG} -r ${DOCKER_INFLUXDB_INIT_RETENTION}
influx bucket create -n ${DOCKER_INFLUXDB_JMETER_BUCKETS} -o ${DOCKER_INFLUXDB_INIT_ORG} -r ${DOCKER_INFLUXDB_INIT_RETENTION}
influx bucket create -n ${DOCKER_INFLUXDB_SOLR_BUCKETS} -o ${DOCKER_INFLUXDB_INIT_ORG} -r ${DOCKER_INFLUXDB_INIT_RETENTION}
influx bucket create -n ${DOCKER_INFLUXDB_HYBRIS_BUCKETS} -o ${DOCKER_INFLUXDB_INIT_ORG} -r ${DOCKER_INFLUXDB_INIT_RETENTION}

