version: '3.5'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb
    container_name: influx
    restart: always
    env_file:
      - ./influx/influxdb.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      ## Username to set for the admin user (Required)
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}

      ## Password to set for the admin user (Required)
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}

      ## Name to set for the initial organization (Required)
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}

      ## Name to set for the initial bucket (Required)
      - DOCKER_INFLUXDB_INIT_BUCKET=¤{INFLUXDB_INIT_BUCKET}

      ##  Duration for the initial bucket’s retention period. If not set, the initial bucket will retain data forever
      ##  INFLUXDB_RETENTION

      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    depends_on:
        - influxdb
    env_file:
      - ./grafana/grafana.env
    volumes:
        - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}