version: '3.5'

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${INFLUXDB_PORT}:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
 
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file:
      - .env
    ports:
      - '8125:8125'

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - influxdb
    env_file:
     - .env
    volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/config.ini:/etc/grafana/grafana.ini:ro
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        - ./grafana/dashboards:/var/lib/grafana/dashboards:rw

volumes:
  grafana_data: {}
  influxdb_data: {}