version: '3.5'

services:

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d/
      - ./influxdb/config:/etc/influxdb2/
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${INFLUXDB_PORT}:8086
 
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file:
      - .env
  mssql_agent:
    image: telegraf
    container_name: mssql_agent
    restart: always
    volumes:
      - ./mssql_agent/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file:
      - .env

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file:
     - .env
    volumes:
        - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
  
  