{
 "title": "MSSQL Server ( Flux syntax )",
 "description": "implement in-depth SQL Server monitoring to ensure that the instances are optimized, healthy, and available",
 "tags": [
  "mssql",
  "flux"
 ],
 "time": { "from": "2022-06-28T04:45:37.399Z", "to": "2022-06-28T16:45:37.399Z" },
 "templating": {
  "list": [
   {
    "name": "myInterval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "DATABASE PROPERTIES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_online\" or r[\"_field\"] == \"db_recovering\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State ONLINE",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_online\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State OFFLINE",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_offline\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "SUSPECT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State SUSPECT",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_suspect\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RECOVERING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RECOVERING",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_recovering\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RECOVERY_PENDING",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_recoveryPending\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RESTORING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RESTORING",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_restoring\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "COUNT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model FULL",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "ENGINE EDITION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model BULK_LOGGED",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"engine_edition\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model BULK_LOGGED",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "SERVER MEMORY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model SIMPLE",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"server_memory\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "KPI | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Idle (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "CPU (%)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_idle_cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "SystemIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "SQL CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"CPU usage %\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "External CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"other_process_cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "USAGE TIME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"CPU Usage (time)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  { "title": "KPI | Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Target Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Target Server Memory (KB) | Memory Manager",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Target Server Memory (KB)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Total Server Memory (KB) | Memory Manager",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Total Server Memory (KB)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Rows Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Rows writes (bytes/sec)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Log Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log writes (bytes/sec)",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"LOG\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"Buffer Pool\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Free list stalls/sec | Buffer Manager",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Free list stalls/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  { "title": "PERFORMANCE COUNTERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Logins/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Logins/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Logouts/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Logouts/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"User Connections\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Processes blocked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Processes blocked\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SQL Re-Compilations/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"SQL Re-Compilations/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Batch req/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Batch Requests/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Transactions/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Log Flushes/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Write Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Write Transactions/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lock Timeouts (timeout > 0)/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Lock Timeouts (timeout > 0)/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lock Timeouts/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Lock Timeouts/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Processes blocked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Processes blocked\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lock Wait Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Lock Wait Count\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Used memory (KB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Used memory (KB)\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"internal\" or r[\"instance\"] == \"default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Database size trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Database | Rows Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Database | Log Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Database I/O | WRITE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Writes | Rows Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Writes | Log Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"LOG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Database I/O | READ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "READ | Rows Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "READ | Log Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"LOG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Database Latency | READ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Reads | Rows (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Reads | Rows (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Database Latency | WRITE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Writes | Rows (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Writes| Log (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"LOG\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}