{
 "title": "MS SQL Server",
 "description": "A custom dashboard to monitor sql server ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SQL UPTIME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1440 }))"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_online\")"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_offline\")"
    }
   ]
  },
  {
   "title": "User Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"User Connections\")"
    }
   ]
  },
  {
   "title": "Restoring",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_restoring\")"
    }
   ]
  },
  {
   "title": "Recovering",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_recovering\")"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_recoveryPending\")"
    }
   ]
  },
  {
   "title": "Suspect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_server_properties\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"db_suspect\")"
    }
   ]
  },
  {
   "title": "Target Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Target Server Memory (KB)\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1024.00}))"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Used memory (KB)\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value / 100024.00}))"
    }
   ]
  },
  {
   "title": "SQL IDLE CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system_idle_cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Reads Latency (ms) | Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_latency_ms\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"ROWS\")\r\n"
    }
   ]
  },
  {
   "title": "SQL CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"CPU usage %\")\r\n  "
    }
   ]
  },
  {
   "title": "Reads Latency (ms) | LOG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_database_io\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_latency_ms\")\r\n  |> filter(fn: (r) => r[\"file_type\"] == \"LOG\")\r\n"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Transactions/sec\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"PEPS_NG_uat\" or r[\"instance\"] == \"Total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Errors/sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"counter\"] == \"Buffer cache hit ratio\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_volume_space\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_space_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mssql\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sqlserver_volume_space\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_space_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}