apiVersion: 1

datasources:
  - name: Hybris JVM
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    # <bool> enable/disable basic auth
    basicAuth: false
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    # <bool> allow users to edit datasources from the UI.
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_HYBRIS_BUCKETS
      tlsSkipVerify: true
    editable: false
