apiVersion: 1

deleteDatasources:
  - name: default
    orgId: 1

datasources:
  - name: Hybris JVM
    type: influxdb
    access: proxy
    url: http://influx:8086
    user: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      password: $GF_SECURITY_ADMIN_PASSWORD