apiVersion: 1

datasources:
  - name: JMeter
    type: influxdb
    access: proxy
    database: jmeter
    url: http://influx:8086
    user: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      password: $GF_SECURITY_ADMIN_PASSWORD