apiVersion: 1

datasources:
  - name: JMeter
    type: influxdb
    access: proxy
    database: jmeter
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    basicAuth: false
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_JMETER_BUCKETS
      tlsSkipVerify: true
