apiVersion: 1

datasources:
  - name: Solr JVM
    type: influxdb
    access: proxy
    database: solr
    url: http://influx:8086
    user: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      password: $GF_SECURITY_ADMIN_PASSWORD