apiVersion: 1

datasources:
  - name: SQL Server
    type: influxdb
    access: proxy
    database: mssql
    url: http://influx:8086
    user: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      password: $GF_SECURITY_ADMIN_PASSWORD