apiVersion: 1

datasources:
  - name: SQL Server
    type: influxdb
    access: proxy
    database: mssql
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    basicAuth: false
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_SQL_SERVER_BUCKETS
      tlsSkipVerify: true
