FROM grafana/grafana
ADD ./provisioning /etc/grafana/provisioning
ADD ./config.ini /etc/grafana/config.ini
ADD ./dashboards /var/lib/grafana/dashboards
ADD ./dashboards/mssql /var/lib/grafana/dashboards/mssql
ADD ./dashboards/solr /var/lib/grafana/dashboards/solr
ADD ./dashboards/jmeter /var/lib/grafana/dashboards/jmeter
ADD ./dashboards/hybris /var/lib/grafana/dashboards/hybris