{
 "title": "New dashboard solr",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "master_pepsBoCMS_CMSItem_default",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Rollbacks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rollbacks\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> filter(fn: (r) => r[\"handler\"] == \"/get\" or r[\"handler\"] ==\"/query\" or r[\"handler\"] ==\"/select\" or r[\"handler\"] ==\"/facet\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_queryhandler\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"errors\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> filter(fn: (r) => r[\"handler\"] == \"/get\" or r[\"handler\"] ==\"/query\" or r[\"handler\"] ==\"/select\" or r[\"handler\"] ==\"/facet\" or r[\"handler\"] ==\"/sql\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Max Docs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_core\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_docs\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "95% Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_queryhandler\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"95th_pc_request_time\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> filter(fn: (r) => r[\"handler\"] == \"/get\" or r[\"handler\"] ==\"/query\" or r[\"handler\"] ==\"/select\" or r[\"handler\"] ==\"/facet\" or r[\"handler\"] ==\"/sql\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "master_pepsBoCMS_CMSItem_default",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_queryhandler\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_requests_per_second\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_queryhandler\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"requests\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_pepsBoCMS_CMSItem_default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "master_peps_Product_default",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"solr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solr_queryhandler\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_requests_per_second\")\r\n  |> filter(fn: (r) => r[\"core\"] == \"master_peps_Product_default\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}